

INSERT INTO sboard2 (ID, APP_USER_ID, BTITLE, BCONTENT, BPASS, BIP, CREATED_AT) 
SELECT (SELECT NVL(MAX(ID), 0) FROM sboard2) + 
ROWNUM, APP_USER_ID, BTITLE, BCONTENT, BPASS, BIP, SYSDATE FROM sboard2;
commit;

select *  from  sboard2  order by id  desc;
INSERT INTO sboard2 (ID, APP_USER_ID, BTITLE, BCONTENT, BPASS, BIP, CREATED_AT) SELECT (SELECT NVL(MAX(ID), 0) FROM sboard2) + ROWNUM, APP_USER_ID, BTITLE, BCONTENT, BPASS, BIP, SYSDATE FROM sboard2;
 